### PR TITLE
Debug placement

### LINKED ISSUE #9: support for special nodes
Are there any intentions to add support for special nodes like:
- cables
- tubes
- liquids (they work, when owning player is online, but buckets are destroyed)
- wires (mesecon/digiline)
- luac

or is that up to user to write translation code?
well, cable-plates are a very special one

### PR DESCRIPTION
**Pull request by SwissalpS**
Seeds still do not work. (except mushrooms and sapplings)
These changes however largely improve item handling and placement of cut nodes.
See the individual commit comments.

I've attached world-edit models of a small test setup:
dibuDemoOrig.we - original setup that was copied, code included. Only the tube and the water needed changing. Also I added pointed_thing modifiers to the letters.
dibuDemoResult.we - the result I got. 1/4 letters worked, so still improvement needed.
dibuDemoMT.we - an empty build setup ready for use. The button in front of luac is the play/pause button. The one to the right(opposite the LCD) is a reset button.
[dibuDemo.zip](https://github.com/BuckarooBanzay/digibuilder/files/11591344/dibuDemo.zip)

Edit: the seeds I tried now work if you add 'down' field in message.

potentially closes #9

### CODE REVIEW

**Comment by BuckarooBanzay** [comment]
LGTM i think :+1: 

Some unrelated notes/fyi's:
* the fakeplayer stuff needs to be in a separate mod someday (the `pipeworks` and `digtron` mods could use that too)
* i'd like to move that mod to the `mt-mods` org at some point

**Comment by SwissalpS** [comment]
yes, I agree, fake_player-mod would be great and simplify a lot

**Comment by OgelGames** [comment]
> fake_player-mod

That's something else that's been on my todo list for a while now... :/

I was thinking of combining it with fake inventory and fake metadata (which would be used by the fake player anyway).

Ugh, I really need to get to actually finishing stuff... or maybe stop starting new projects 🤔

**Comment by SwissalpS** [comment]
OK, this is as far as I can get in the time I can make for this PR.

I'd like to make a test-node or other mechanic to test on all registered items outputting result to file/terminal. It would have to include surrounding nodes if resulting node is not the same as item used.

I wasn't sure about how to go about sending digiline messages from a mod.
The hope of this procedure is to find items that a) crash server b) don't result in the same node as item and c) to detect which end up in shifted position without and with supporting nodes.

Edit: just saw that mtt is already prepared. I had to disable loading player.lua though to get it running.

**Comment by BuckarooBanzay** [comment]
> or maybe stop starting new projects thinking

heh, or just embrace it, worked for me so far :shrug: 

> OK, this is as far as I can get in the time I can make for this PR.

LGTM i think, you tested this, right?

**Comment by SwissalpS** [comment]
> you tested this, right?
yes, not every possible node/item yet though.

**Pull request merged**
