### PR TITLE
infinite loop patch

### PR DESCRIPTION
**Pull request by SwissalpS**
as suggested by Huhhila

### CODE REVIEW

**Comment by OgelGames** [comment]
```
digiline.lua:30:1: line contains only whitespace
```
It's always the whitespace :P

**Comment by BuckarooBanzay** [comment]
thanks :+1:

**Comment by SwissalpS** [comment]
maybe it would be better to move the check above channel test, as it doesn't really matter what channel it is sent on, builders can ignore error messages

**Comment by BuckarooBanzay** [comment]
> maybe it would be better to move the check above channel test, as it doesn't really matter what channel it is sent on, builders can ignore error messages

done :+1:

**Pull request merged**
